# Data Structures

A data structure is a way of **organizing and storing data** in a computer program so that it can be accessed and used **efficiently**. 

Data Structures provide a way to optimize the **storage** and **retrieval** of data, and also facilitate efficient algorithms for **manipulating** the data. 

Some common use cases for data structures include:

- **Storing large amounts of data**: When you have a large dataset, using an appropriate data structure can help you store and access the data efficiently.

- **Searching and sorting data**: Data structures like trees and graphs can be used to search and sort data quickly.

- **Implementing algorithms:** Data structures can be used to implement various algorithms, such as sorting, searching, and graph traversal.

- **Caching and memory management:** Data structures like caches and pools can be used to improve performance and manage memory effectively.

- **Modeling real-world objects:** Data structures can be used to model real-world objects and systems, such as social networks or road networks.

## Arrays

An array is a collection of elements of the same data type stored in contiguous memory locations.

Arrays store a **fixed number of elements of the same type**, and they provide efficient ways to access and manipulate elements.

Arrays are not built in Python programming but can be represented by **lists** or with a third-party library such as **NumPy**.

In [ ]:
## Array created using lists
my_array = [1, 2, 3, 4, 5]

In [ ]:
## Array created using numpy array
import numpy as np
my_array = np.array([1, 2, 3, 4, 5])

### Indexing

Arrays can be manipulated using indexing, the *first element* has an index of *0*, and the *last element* has an index of *n-1*, where *n* is the size of the array.

The syntax for indexing is as follows:
`my_array[index]`

In [ ]:
## Indexing
my_array = [1, 2, 3, 4, 5]
print(f"Original array: {my_array}") # Output: [1, 2, 3, 4, 5]

# Length of the array
n = len(my_array) 
print(f"Length of the array: {n}") # Output: 5

# Indexing the first element, Output: 1
print(f"First element: {my_array[0]}")

# Indexing last element
print(f"Last element: {my_array[n - 1]}") # Output: 5

# Modify an element by index
my_array[2] = 8 
print(f"Modified array: {my_array}") # Output: [1, 2, 8, 4, 5]

# Negative indexing
# Last element is -1
print(f"Last element: {my_array[-1]}") # Output: 5
print(f"Second last element: {my_array[-2]}") # Output: 4

Original array: [1, 2, 3, 4, 5]
Length of the array: 5
First element: 1
Last element: 5
Modified array: [1, 2, 8, 4, 5]
Last element: 5
Second last element: 4


### Slicing

Slicing is a way to access a specific subset of elements in an array. It allows you to exctract a portion of the array by specifying the *start* and *end* indices of the slice.

The syntax for slicing is as follows:
`my_array[start_index:end_index:step]`

In [ ]:
## Slicing
my_array = [1, 2, 3, 4, 5]

# Slicing the first three elements
print(f"Slicing first three elements: {my_array[0:3]}") # Output: [1, 2, 3]

# Slicing every other element
print(f"Slicing every other elenent by step of two: {my_array[::2]}") # Output: [1, 3, 5]

# Slicing the last two elements
print(f"Slicing the last two elements: {my_array[-2:]}") # Output [4, 5]

Slicing first three elements: [1, 2, 3]
Slicing every other elenent by step of two: [1, 3, 5]
Slicing the last two elements: [4, 5]


### NumPy arrays

NumPy arrays are similar to lists in Python, but provide several advantages:

- **Homogeneous data**: All the elements should have the same data type, which makes it more efficient to store and manipulate large datasets of numerical data.

- **Multidimensional**: A NumPy array can have multiple dimensions which makes it easy to represent tabular format.

- **Fast computation**: NumPy arrays are implemented in C and optimized for performance, which makes them much faster than Python lists for numerical computation.

In [ ]:
import numpy as np

# Create a 2-D array using numpy
np_array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"2-D Array: \n {np_array_2d}") # Output: [[1 2 3] [4 5 6] [7 8 9]
print(f"Shape of the array: {np_array_2d.shape}") # Output: (3, 3)

# Indexing a 2-D array
print(f"Element in pos [1, 2]: {np_array_2d[1, 2]}") #Output: 6

# Slicing a 2-D array
print(f"Slicing subset array: {np_array_2d[1:, 1:]}") # Output: [[5 6] [8 9]]

# Statistical built in functions in Numpy
print(f"Mean of all data in np_array_2d: {np.mean(np_array_2d)}") # Output: 5.0
print(f"Std of all data in np_array_2d: {np.std(np_array_2d)}") # Output: 2.581988897471611

2-D Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of the array: (3, 3)
Element in pos [1, 2]: 6
Slicing subset array: [[5 6]
 [8 9]]
Mean of all data in np_array_2d: 5.0
Std of all data in np_array_2d: 2.581988897471611


Numpy provides multiple vectorized operations, the use of vectorization allows numpy to perform matrix operations more efficiently by avoiding many for loops. (See [Top 10 Matrix Operations in Numpy](https://towardsdatascience.com/top-10-matrix-operations-in-numpy-with-examples-d761448cb7a8)

In [ ]:
# Element wise multiplication using loops
def loop_mult(a, b):
  result = np.zeros_like(a)

  for i in range(len(a)):
    result[i] = a[i] * b[i]
  return result

# Element wise multiplication using vectorized NumPy operation
def vectorized_mult(a, b):
  return a * b

In [ ]:
a = np.array([1, 2, 3, 5])
b = np.array([6, 7, 8, 9])
print(f"Element wise multiplication using loops: {loop_mult(a, b)}") # Output: [ 6 14 24 45]
print(f"""
  Element wise multiplication using vectorized Numpy operations: 
  {vectorized_mult(a, b)}
""") # Output: [ 6 14 24 45]

Element wise multiplication using loops: [ 6 14 24 45]

  Element wise multiplication using vectorized Numpy operations: 
  [ 6 14 24 45]



Impact of vectorized operations for large datasets

In [ ]:
a = np.arange(0, 10000000) # Ten million elements
b = np.arange(10000000, 20000000)

In [ ]:
%%time
loop_mult(a, b)

CPU times: user 2.4 s, sys: 30.7 ms, total: 2.43 s
Wall time: 2.46 s


array([              0,        10000001,        20000004, ...,
       199999910000009, 199999940000004, 199999970000001])

In [ ]:
%%time
vectorized_mult(a, b)

CPU times: user 18.1 ms, sys: 9.4 ms, total: 27.5 ms
Wall time: 28.7 ms


array([              0,        10000001,        20000004, ...,
       199999910000009, 199999940000004, 199999970000001])

### Code challenge

Write a Python function that takes in an array of integers and returns the sum of all the even numbers in the array.

> Hint: You can use list comprehensions, the reduce function, or a for loop.

In [21]:
from typing import List
def sum_even_numbers(arr: List[int]) -> int:
    ## TODO: Write your solution here
    pass

assert sum_even_numbers([1, 2, 3, 4, 5, 6]) == 12
assert sum_even_numbers([7, 8, 9, 10]) == 18
assert sum_even_numbers([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) == 20

12


## Lists

A list is a collection of values, which can be of any data type. Lists are mutable, which means you can add, remove or modify elements in a list after it has been created.

The indexing is similar to arrays, starting from 0.
The syntax for slicing is similar to arrays also:
`my_array[start_index:end_index:step]`

In [ ]:
my_list = [1, 2, 3, "four", 5.0]

# Indexing list
print(f"Value at the position 3: {my_list[3]}") # Output four

# Modifying element
my_list[2] = "three"
print(f"Modified list: {my_list}") # Output [1, 2, "three", "four", 5.0]

# Slicing list
print(f"Sliced list: {my_list[2:4]}") # Output ['three', 'four']

Value at the position 3: four
Modified list: [1, 2, 'three', 'four', 5.0]
Sliced list: ['three', 'four']


### Built-in Methods

Lists have several built-in methods that can be used to manipulate and access the data stored in them.

In [ ]:
numbers = [40, 2, 3, 4, 5]

# Adds an item to the end of the list
numbers.append(6)
print(f"List with 6 appended to the end of the list: {numbers}") # Output: [40, 2, 3, 4, 5, 6]

# Adds all items from a different list to the end of the list
numbers2 = [7, 8, 9, 10]
numbers.extend(numbers2)
print(f"List extended: {numbers}") # Output: [40, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Insert an item at a specified index in the list
numbers.insert(2, 2.5)
print(f"List with new element inserted at position 2: {numbers}") # Output: [40, 2, 2.5, 3, 4, 5, 6, 7, 8, 9, 10]

# Remove the first ocurrence of an item from the list
numbers.remove(2.5)
print(f"List with 2.5 removed: {numbers}") # Output: [40, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Remove and return the item at the specified index in the list
pop_element = numbers.pop(-1)
print(f"The number {pop_element} has been removed from the list: {numbers}") # Output: [40, 2, 3, 4, 5, 6, 7, 8, 9]

# Return the index of the first occurence of an item in the list
print(f"The number 5 is at the position: {numbers.index(5)}") #Output: 4

# Return the number of times an element appears in the list
print(f"The number 7 appears {numbers.count(7)} time(s) in the list") # Output: 1

numbers.sort()
print(f"The list {numbers} is sorted in ascending order") # Output: [2, 3, 4, 5, 6, 7, 8, 9, 40]

numbers.reverse()
print(f"The list {numbers} is reversed") # Output: [40, 9, 8, 7, 6, 5, 4, 3, 2] 

List with 6 appended to the end of the list: [40, 2, 3, 4, 5, 6]
List extended: [40, 2, 3, 4, 5, 6, 7, 8, 9, 10]
List with new element inserted at position 2: [40, 2, 2.5, 3, 4, 5, 6, 7, 8, 9, 10]
List with 2.5 removed: [40, 2, 3, 4, 5, 6, 7, 8, 9, 10]
The number 10 has been removed from the list: [40, 2, 3, 4, 5, 6, 7, 8, 9]
The number 5 is at the position: 4
The number 7 appears 1 time(s) in the list
The list [2, 3, 4, 5, 6, 7, 8, 9, 40] is sorted in ascending order
The list [40, 9, 8, 7, 6, 5, 4, 3, 2] is reversed


### IN

The `in` operator is used to check if a particular element is present in a given list or not. It returns a Boolean value `True` if the element is present in the list, and `False` if it is not.

The syntax for using it is as follows:
`element in list`

In [ ]:
my_list = [1, 2, 3, 4, 5]
print(f"The number 4 is present in my list: {3 in my_list}") # Output: True
print(f"The numer 9 is NOT present in my list: {9 not in my_list}") # Output: True

The number 4 is present in my list: True
The numer 9 is NOT present in my list: True


The `in` operator can be used in combination with a `for` loop to iterate over the elements of a list.

In [ ]:
numbers = [1, 2, 3, 4, 5]
for number in numbers:
  if number % 2 == 0:
    print(f"The number {number} is even")

The number 2 is even
The number 4 is even


### Range

The `range` operator is used to generate a sequence of numbers. The sequence can be converted into a list using the `list` constructor.

In [ ]:
numbers = list(range(1, 6))
print(numbers) # Output: [1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]


The `range` operator is often used in combination with a `for` loop to iterate over a sequence of numbers

In [ ]:
for i in range(1, 6):
  print(i)

1
2
3
4
5


### Unpacking lists

In Python you can use the unpacking operator (`*`) to unpack a list into individual elements. 

In [ ]:
# Unpack list by elements
my_list = [1, 2, 3]
a, b, c = my_list
print(f"a: {a}, b: {b}, c: {c}") # Output: a: 1, b: 2, c: 3

# Unpack a portion of the list
a, *rest = my_list
print(f"a: {a}, rest: {rest}") # Output: a: 1, rest: [2, 3]

# Pass unpacked elements as arguments of a function
sum_a_b_c = lambda a, b, c: a + b + c
print(f"Sum result using unpacking: {sum_a_b_c(*my_list)}") # Output: 6


a: 1, b: 2, c: 3
a: 1, rest: [2, 3]
Sum result using unpacking: 6


### Code challenge

Write a Python function that takes in a list of integers and returns a new list with all the duplicates removed, sorted in ascending order.

> You can use a for loop and the built-in list methods

In [27]:
from typing import List

def remove_duplicates_sorted(arr: List[int]) -> List[int]:
    # TODO: Write your solution here
    pass

assert remove_duplicates_sorted([3, 1, 5, 3, 2, 1, 6, 7, 7, 2]) == [1, 2, 3, 5, 6, 7]
assert remove_duplicates_sorted([9, 8, 7, 6, 5, 4, 3, 2, 1]) == [1, 2, 3, 4, 5, 6, 7, 8, 9]
assert remove_duplicates_sorted([1, 1, 1, 1, 1]) == [1]


AssertionError: ignored

## Tuples

A tuple is an immutable collection of ordered elements. Tuples are similar to lists, but they cannot be modified once they are created. 

This means that you cannot modify their elements or add a new element to the tuple.

Tuples are created using parenthesis or the `tuple()` constructor.

In [ ]:
# Create a tuple using parenthesis
my_tuple = (1, 2, 3, 4, 5)

# Create a tuple using seperated by comma values
my_other_tuple = "1", "2", "3", "4", "5"

### Indexing and slicing

Tuples can be accessed using slicing and indexing, just like a list

In [ ]:
print(f"Element of tuple at the position 0: {my_tuple[0]}") # Output: 1
print(f"Slicing a tuple: {my_tuple[1:3]}") # Output: (2, 3)

Element of tuple at the position 0: 1
Slicing a tuple: (2, 3)


### Using tuples to return values of a function

A general use of tuples is to return multiple values from a function.

In [ ]:
def get_name_and_age():
    name = "Alice"
    age = 25
    return name, age

name, age = get_name_and_age()
print(name) # Output: "Alice"
print(age) # Output: 25

Alice
25


### Code challenge

Write a function that takes in a tuple of integers and returns a new tuple with the odd numbers in the original tuple, sorted in descending order.

> Hint: You can use a list comprehension, a filter or a for loop.

In [54]:
from typing import Tuple

def odd_numbers_descending(tup: Tuple[int]) -> Tuple[int]:
    ## TODO: Write your code here
    pass

assert odd_numbers_descending((3, 1, 5, 2, 7, 6, 8, 9)) == (9, 7, 5, 3, 1)
assert odd_numbers_descending((2, 4, 6, 8)) == ()
assert odd_numbers_descending((1, 3, 5, 7, 9)) == (9, 7, 5, 3, 1)

## Dictionaries

A dictionary is a data structure that stores data in *key-value* pairs. Dictionaries are *indexed* by *keys*, which can be any immutable type such as strings, numbers, or tuples.

The Python dictionaries have the following characteristics:

- **Unordered**: The items in the dictionary are not ordered, which means that the order of the items can change and is not preserved. (OrderedDict is a subclass of dictionaries that have extra capabilities to remember insertion order).
- **Mutable:**: Dictionaries are mutable, you can add, remove, and modify items after the dictionary is created.
- **Unique keys:** Each key in the dictionary must be unique.
- **Variable value types**: The values in a dictionary can be of any type, including other dictionaries, lists, tuples, and even functions.
- **Efficient lookup:** Provide fast lookups by key, which makes them useful for applications such as caching and memoization. (See [Memoization in Python](https://www.knowledgehut.com/blog/programming/memoization-in-python)

In [ ]:
# Create a dictionary
person = { 'name': 'John', 'age': 30, 'city': 'New York' }

### Indexing

To access a value in a dictionary, you can use the key as index.

The syntax is as following:
`dictionary[key]`

In [ ]:
# Access a value using a key
print(f"The name of the person is: {person['name']}") # Output: John

# Add a new key-value pair to dictionary
person['occupation'] = 'Engineer'
print(f"The occupation of the person is: {person['occupation']}") # Output: Engineer

# Modify an existing key-value pair
person['age'] = 31
print(f"The current age of the person is: {person['age']}") # Output: 31

# Delete existing key-value pair
del person['city']
print(f"Modified dictionary, city deleted: {person}") # Output: {'name': 'John', 'age': 31, 'occupation': 'Engineer'}


The name of the person is: John
The occupation of the person is: Engineer
The current age of the person is: 31
Modified dictionary, city deleted: {'name': 'John', 'age': 31, 'occupation': 'Engineer'}


### Built-in Methods

Python provides a number of built-in methods for dictionaries to perform various operations.

In [ ]:
person = { 'name': 'John', 'lastname': 'Cena', 'age': 30, 'city': 'New York' }
person_new_ref = person

# Modifying the new referenced dict modifies also the original dict
person_new_ref['name'] = 'Shawn'
print(f"New reference dict modified: {person_new_ref}")
print(f"Original dict modified: {person}")

# Modifying the shallow copy dict does not change the original one
copy_person = person.copy()
copy_person['lastname'] = 'Michaels'
print(f"This is the shallow copy modified: {copy_person}")
print(f"This is the original dict unmodified: {person}")

# Get the key-value pair in dictionary or a default value
print(f"The age of the person is: {person.get('age', 'Not available')} years")
print(f"The occupation of the person is: {person.get('occupation', 'Not available')}")

# Get the key-value pairs as a list of tuples
print(f"The key value pairs are: {person.items()}")

# Get the keys of a dict
print(f"The keys are: {person.keys()}")

# Get the values of a dict
print(f"The values are: {person.values()}")

New reference dict modified: {'name': 'Shawn', 'lastname': 'Cena', 'age': 30, 'city': 'New York'}
Original dict modified: {'name': 'Shawn', 'lastname': 'Cena', 'age': 30, 'city': 'New York'}
This is the shallow copy modified: {'name': 'Shawn', 'lastname': 'Michaels', 'age': 30, 'city': 'New York'}
This is the original dict unmodified: {'name': 'Shawn', 'lastname': 'Cena', 'age': 30, 'city': 'New York'}
The age of the person is: 30 years
The occupation of the person is: Not available
The key value pairs are: dict_items([('name', 'Shawn'), ('lastname', 'Cena'), ('age', 30), ('city', 'New York')])
The keys are: dict_keys(['name', 'lastname', 'age', 'city'])
The values are: dict_values(['Shawn', 'Cena', 30, 'New York'])


### Iterate over a dictionary

In [ ]:
person = { 'name': 'John', 'lastname': 'Cena', 'age': 30, 'city': 'New York' }

# By default, iterating over a dict iterates over its keys.
print("Iterate over keys")
for key in person:
  print(f"Key: {key}")

# Iterate over items Tuple: (key, value)
print("Iterate over items")
for key,value in person.items():
  print(f"Key: {key}, Value: {value}")

Iterate over keys
Key: name
Key: lastname
Key: age
Key: city
Iterate over items
Key: name, Value: John
Key: lastname, Value: Cena
Key: age, Value: 30
Key: city, Value: New York


### Unpacking dicts

Similar to lists, you can use the unpacking operator (`**`) to unpack a dictionary into individual key-value pairs.

In [ ]:
my_dict = { 'a': 1, 'b': 2, 'c': 3}

# Use unpacking to create a new dictionary by reusing an existing one
new_dict = {'d': 4, **my_dict}
print(f"New dictionary: {new_dict}") # Output: {'d': 4, 'a': 1, 'b': 2, 'c': 3}

# Use unpacking to pass elements as function arguments
person = { 'name': 'John', 'lastname': 'Cena', 'age': 30, 'city': 'New York' }
print_person_details = (
    lambda name, lastname, age, city: 
    print(f"Name: {name}, Lastname: {lastname}, Age: {age}, City: {city}")
)
print_person_details(**person)

New dictionary: {'d': 4, 'a': 1, 'b': 2, 'c': 3}
Name: John, Lastname: Cena, Age: 30, City: New York


### Work with JSON data using dicts

A use case of dictionaries could be to manage data from a JSON string. 

We use the library `json` which parses a JSON string into a python dictionary using the method `loads`.

In [ ]:
import json
person_string = '{ "name": "John", "lastname": "Cena", "age": 30, "city": "New York" }'

# Parse the JSON string into a dictionary using the json.loads() method
person_dict = json.loads(person_string)

# Modify some key-value pairs
person_dict['name'] = 'Shawn'
person_dict['lastname'] = 'Michaels'

# Print the modified dictionary
print_person_details(**person_dict)

Name: Shawn, Lastname: Michaels, Age: 30, City: New York


### Code challenge

Write a Python function that takes in a list of dictionaries, where each dictionary contains information about a book, including its title, author, and price. The function should return a new dictionary that contains the average price of books written by each author.

> Hint: You can use dictionary comprehension

In [81]:
from typing import List, Dict

def average_price_by_author(books: List[Dict[str, float]]) -> Dict[str, float]:
    ## TODO: Write your code here
    pass

books = [
    {'title': 'The Great Gatsby', 'author': 'F. Scott Fitzgerald', 'price': 12.99},
    {'title': 'To Kill a Mockingbird', 'author': 'Harper Lee', 'price': 9.99},
    {'title': 'The Catcher in the Rye', 'author': 'J.D. Salinger', 'price': 10.99},
    {'title': 'The Great Gatsby', 'author': 'F. Scott Fitzgerald', 'price': 15.99},
    {'title': 'To Kill a Mockingbird', 'author': 'Harper Lee', 'price': 7.99},
    {'title': 'The Catcher in the Rye', 'author': 'J.D. Salinger', 'price': 12.99}
]

assert average_price_by_author(books) == {'F. Scott Fitzgerald': 14.49, 'Harper Lee': 8.99, 'J.D. Salinger': 11.99}

AssertionError: ignored

## Stacks

A Stack is a linear data structure that follows the *Last-In, First-Out (LIFO)* principle. 

This means that the last item added to the stack is the first item to be removed. 

Stacks are commonly used in algorithms and programming to keep track of function calls, undo operations, and other operations where the order of processing is important.

The three primitive operations associated with stacks are:

- **Push**: Add an element to the stack
- **Pop**: Remove an element from the stack
- **Peek**: Get the topmost element of the stack



### Stack using lists

A Stack can be implemented using a list in python. The drawback is that the insertion (push) and deletion (pop) time complexity grows as the size of the list grows also, at the pace of *O(n)*. (See [What is time complexity?](https://www.mygreatlearning.com/blog/why-is-time-complexity-essential/))

In [ ]:
my_stack = []
my_stack.append('A') # Push A
my_stack.append('B') # Push B
my_stack.append('C') # Push C

print(f"Stack with appended elements: {my_stack}") # Output: ['A', 'B', 'C']

print(f"Pop {my_stack.pop()}") # Pop C
print(f"Pop {my_stack.pop()}") # Pop B
print(f"Pop {my_stack.pop()}") # Pop A

print(f"Stack after removing elements: {my_stack}") # Output: []

Stack with appended elements: ['A', 'B', 'C']
Pop C
Pop B
Pop A
Stack after removing elements: []


### Stack using Collections.deque

In Python, the collections module provides a deque class that can be used to implement a stack. A deque is a double-ended queue that supports adding and removing elements from both ends, making it an ideal data structure for implementing a stack.

Because a deque is optimized for adding and removing elements from both ends, it provides better performance (approximately *O(1)*) for stack operations than a list.

In [ ]:
from collections import deque

my_stack = deque()

my_stack.append('A') # Push A
my_stack.append('B') # Push B
my_stack.append('C') # Push C

print(f"Stack with appended elements: {my_stack}") # Output: deque(['A', 'B', 'C'])

print(f"Pop {my_stack.pop()}") # Pop C
print(f"Pop {my_stack.pop()}") # Pop B
print(f"Pop {my_stack.pop()}") # Pop A

print(f"Stack after removing elements: {my_stack}") # deque([])

Stack with appended elements: deque(['A', 'B', 'C'])
Pop C
Pop B
Pop A
Stack after removing elements: deque([])


### Code challenge

Write a Python function that takes in a string of parentheses(`(` and `)`) and returns `True` if the parentheses are balanced, and `False` otherwise. 

In [86]:
from collections import deque

def check_parentheses(parentheses: str):
  stack = deque()
  ## TODO: Write your code here
  pass


assert check_parentheses("()")      # should return True
assert check_parentheses("(())")      # should return True
assert check_parentheses("(()())")    # should return True
assert not check_parentheses("((())")     # should return False
assert not check_parentheses("())(")      # should return False


## Queues

In Python, a queue is a data structure that follows the *First-In, First-Out (FIFO)* principle. This means that the first item added to the queue is the first item to be removed. Queues are commonly used in algorithms and programming to manage tasks that need to be processed in the order they are received.

The primmitive operations associated with a queue are:

- **Enqueue**: Adds an element to the end of the queue.
- **Dequeue**: Removes and return the first element from the front of the queue.
- **Peek**: Returns the value of the first element in the queue without removing it.
- **Size**: Return the number of elements in the queue.


### Queues using lists

A list in Python can be used as a queue, however, lists are slow for this purpose because inserting or deleting an element at the beginning requires shifting all of the other elements by one, requiring *O(n)* time.


In [ ]:
my_queue = []
my_queue.append('A') # Enqueue A
my_queue.append('B') # Enqueue B
my_queue.append('C') # Enqueue C

print(f"Queue with appended elements: {my_queue}") # Output: ['A', 'B', 'C']

print(f"Dequeue {my_queue.pop(0)}") # Dequeue A
print(f"Dequeue {my_queue.pop(0)}") # Dequeue B
print(f"Dequeue {my_queue.pop(0)}") # Dequeue C

print(f"Queue after removing elements: {my_queue}") # Output: []

Queue with appended elements: ['A', 'B', 'C']
Dequeue A
Dequeue B
Dequeue C
Queue after removing elements: []


### Queues using Collections.deque

The `deque` class in the Collections module can be used to create a queue.

Because a deque is optimized for adding and removing elements from both ends, it provides better performance (approximately *O(1)*) for queues operations than a list.

In [ ]:
from collections import deque

my_queue = deque()

my_queue.append('A') # Enqueue A
my_queue.append('B') # Enqueue B
my_queue.append('C') # Enqueue C

print(f"Queue with appended elements: {my_queue}") # Output: deque(['A', 'B', 'C'])

print(f"Dequeue {my_queue.popleft()}") # Dequeue A
print(f"Dequeue {my_queue.popleft()}") # Dequeue B
print(f"Dequeue {my_queue.popleft()}") # Dequeue C

print(f"Queue after removing elements: {my_queue}") # deque([])

Queue with appended elements: deque(['A', 'B', 'C'])
Dequeue A
Dequeue B
Dequeue C
Queue after removing elements: deque([])


## Trees

A Tree is a data structure that consists of a *collection of nodes connected by edges or branches*.
Each node represents an element in the tree and the edges represent the relationship between the elements.
The first node in the tree is called *root*, and each node can have zero or more *child* nodes.

Trees are often used to represent hierarchical structures, such as file systems, organization charts, or family trees. They can also be used to implement various algorithms, such as searching, sorting, and data compression. 

### Binary tree

A binary tree is a type of tree in which each node can have **at most two child nodes**, referred to as the *left child* and *right child*. In a binary tree, the left child is always *less than* to the parent node, and the right child is always *greater than* to the parent node. This is called the *binary search property*, and it allows for efficient searching and sorting of data.

A binary tree can be implemented in python using classes and objects.

In [7]:
class Node:
  def __init__(self, data) -> None:
    self.data = data
    self.left_child = None
    self.right_child = None

class BinaryTree:
  def __init__(self):
    self.root = None

  def insert(self, data):
    if self.root is None:
      self.root = Node(data)
    else:
      self._insert(data, self.root)

  def _insert(self, data, node):
    if data < node.data:
      if node.left_child is None:
        node.left_child = Node(data)
      else:
        self._insert(data, node.left_child)
    elif data > node.data:
      if node.right_child is None:
        node.right_child = Node(data)
      else:
        self._insert(data, node.right_child)
    else:
      print("Value already exists in the tree")
    
  def print_tree(self, traversal_type):
      return self.preorder_print(self.root, "")

  def preorder_print(self, start, traversal):
      if start:
          traversal += (str(start.data) + "-")
          traversal = self.preorder_print(start.left_child, traversal)
          traversal = self.preorder_print(start.right_child, traversal)
      return traversal


In [8]:
binary_tree = BinaryTree()
binary_tree.insert(1)
binary_tree.insert(5)
binary_tree.insert(7)
binary_tree.insert(9)
binary_tree.insert(11)
binary_tree.print_tree("preorder")

'1-5-7-9-11-'

## Heaps

A heap is a specialized tree-based data structure that is used to efficiently maintain a collection of elements with priority. 

A heap is a **complete binary tree**, which means that all levels of the tree are fully filled except possibly the last level, which is filled from left to right. 

In a heap, each node has a value or a key that represents its **priority**, and the value or key of each parent node is less than or equal to the value or key of its children nodes.

There are two main types of heaps: 

- **Min-heap:** In a min-heap, the value or key of each parent node is less than or equal to the value or key of its children nodes, and the smallest element is always at the root of the tree. 

- **Max-heap:** In a max-heap, the value or key of each parent node is greater than or equal to the value or key of its children nodes, and the largest element is always at the root of the tree.

In Python, heaps can be implemented using the built-in `heapq` module, which provides functions for creating, manipulating, and accessing heaps.

In [6]:
import heapq
data = [3, 5, 1, 2, 6, 4]

# Create a heap from a list
heapq.heapify(data)

# Print the content of the heap
print(f"The heap contents are: {data}")

# Remove the smallest element in the heap
smallest = heapq.heappop(data)
print(f"The smallest element: {smallest}, has been removed from: {data}")

The heap contents are: [1, 2, 3, 5, 6, 4]
The smallest element: 1, has been removed from: [2, 4, 3, 5, 6]
